"use client";

import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import Nav from "@/components/Nav";
import { ArrowLeft, Bell, CheckCircle2, Lock, MapPin, ShieldCheck, UserRound } from "lucide-react";

export default function ProfilePage() {
  const account = useQuery(api.accounts.me);
  const isAdvocate = account?.accountType === "advocate";
  return <div className="min-h-screen bg-[#f5f7fb] text-[#081a33]"><Nav /><main className="page-container max-w-4xl space-y-6 py-8"><Link href={isAdvocate ? "/lawyer-dashboard" : "/citizen-dashboard"} className="inline-flex items-center gap-2 text-sm font-bold text-blue-700"><ArrowLeft size={15} /> Back to dashboard</Link><section className="card overflow-hidden p-0"><div className="h-32 bg-gradient-to-r from-[#081a33] via-blue-900 to-blue-600" /><div className="px-6 pb-7 sm:px-8"><div className="-mt-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="flex h-20 w-20 items-center justify-center rounded-3xl border-4 border-white bg-blue-50 text-blue-700 shadow-xl"><UserRound size={32} /></div><span className="badge-success w-fit"><CheckCircle2 size={14} className="mr-1" /> Account active</span></div><div className="mt-5"><p className="section-label">{isAdvocate ? "ADVOCATE PROFILE" : "PERSONAL PROFILE"}</p><h1 className="mt-2 text-3xl font-black">{account?.name || "Complete your profile"}</h1><p className="mt-2 text-sm text-slate-500">{account?.email || "Your account email"}</p></div></div></section><div className="grid gap-6 lg:grid-cols-2"><section className="card"><h2 className="text-xl font-black">Profile information</h2><div className="mt-5 space-y-4"><Field label="Display name" value={account?.name || "Not added yet"} /><Field label="Email address" value={account?.email || "Not available"} /><Field label="Account type" value={isAdvocate ? "Advocate" : "Citizen"} /><Field label="Location" value="Add your city in settings" icon={<MapPin size={15} />} /></div><button className="btn mt-6 w-full">Edit profile</button></section><section className="card"><h2 className="text-xl font-black">Security and preferences</h2><div className="mt-5 space-y-3"><Option icon={Lock} title="Password and security" text="Manage your sign-in security" /><Option icon={Bell} title="Notifications" text="Control important updates" /><Option icon={ShieldCheck} title="Privacy controls" text="Review how your information is used" /></div><p className="mt-6 text-xs leading-5 text-slate-500">Your legal information is handled with privacy-conscious workflows. AI-generated information is for general information and research purposes, not legal advice.</p></section></div></main></div>;
}
function Field({ label, value, icon }: { label: string; value: string; icon?: React.ReactNode }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-1 flex items-center gap-1 text-sm font-bold">{icon}{value}</p></div>; }
function Option({ icon: Icon, title, text }: { icon: typeof Lock; title: string; text: string }) { return <button className="flex w-full items-center gap-3 rounded-2xl border border-slate-100 p-3 text-left transition hover:bg-slate-50"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon size={17} /></span><span><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-slate-500">{text}</span></span></button>; }
